In [1]:
import numpy as np 

## Task 1

In [2]:
data1, data2 = np.random.normal(size=(4, 3)), np.random.uniform(size=(3, 4))
dataset = [data1, data2]
for data in dataset:
    print(f'noramal distribution:\n {data}')
?np.random.normal

noramal distribution:
 [[-0.46476243 -0.55800005  0.15796423]
 [ 0.52808353 -0.26334792  0.55359871]
 [ 0.36578814 -0.44086894 -0.43840096]
 [ 0.14138056  0.02824412 -0.43159136]]
noramal distribution:
 [[0.44070814 0.78428961 0.71698191 0.85093412]
 [0.49595484 0.47507437 0.79897587 0.66162029]
 [0.34445609 0.15005364 0.6427049  0.01287034]]


Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the ``normal`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Out

In [3]:
for data in dataset:
    print(f'info:{np.info(data)}\n', 32*'=')
?np.info

class:  ndarray
shape:  (4, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1a24bb0
byteorder:  little
byteswap:  False
type: float64
info:None
class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x152afe0
byteorder:  little
byteswap:  False
type: float64
info:None


Signature:
np.info(
    object=None,
    maxwidth=76,
    output=<ipykernel.iostream.OutStream object at 0x7f0059283910>,
    toplevel='numpy',
)
Docstring:
Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.inf

In [4]:
for data in dataset:
    print(f'sort:\n {np.sort(data)}\n',32*'=')
?np.sort

sort:
 [[-0.55800005 -0.46476243  0.15796423]
 [-0.26334792  0.52808353  0.55359871]
 [-0.44086894 -0.43840096  0.36578814]
 [-0.43159136  0.02824412  0.14138056]]
sort:
 [[0.44070814 0.71698191 0.78428961 0.85093412]
 [0.47507437 0.49595484 0.66162029 0.79897587]
 [0.01287034 0.15005364 0.34445609 0.6427049 ]]


Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecif

In [5]:
for data in dataset:
    print(f' cumsum :\n {data.cumsum(axis=0)}\n')
?np.cumsum

 cumsum :
 [[-0.46476243 -0.55800005  0.15796423]
 [ 0.0633211  -0.82134796  0.71156293]
 [ 0.42910923 -1.2622169   0.27316198]
 [ 0.5704898  -1.23397279 -0.15842938]]

 cumsum :
 [[0.44070814 0.78428961 0.71698191 0.85093412]
 [0.93666298 1.25936397 1.51595778 1.51255441]
 [1.28111907 1.40941761 2.15866268 1.52542475]]



Signature: np.cumsum(a, axis=None, dtype=None, out=None)
Docstring:
Return the cumulative sum of the elements along a given axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    Axis along which the cumulative sum is computed. The default
    (None) is to compute the cumsum over the flattened array.
dtype : dtype, optional
    Type of the returned array and of the accumulator in which the
    elements are summed.  If `dtype` is not specified, it defaults
    to the dtype of `a`, unless `a` has an integer dtype with a
    precision less than that of the default platform integer.  In
    that case, the default platform integer is used.
out : ndarray, optional
    Alternative output array in which to place the result. It must
    have the same shape and buffer length as the expected output
    but the type will be cast if necessary. See `ufuncs-output-type` for
    more details.

Returns
-------
cumsum_along_axis : ndarray.
    A new array holding the resul

In [6]:
for data in dataset:
    print(f'\nmin: {data.min(axis=0)}')
?np.min

Signature:
np.min(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the minimum of an array or minimum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the minimum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See `ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is passed


min: [-0.46476243 -0.55800005 -0.43840096]

min: [0.34445609 0.15005364 0.6427049  0.01287034]


In [7]:
for data in dataset:
    print(f'argmax: {data.argmax(axis=1)}')
?np.argmax

Signature: np.argmax(a, axis=None, out=None)
Docstring:
Returns the indices of the maximum values along an axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    By default, the index is into the flattened array, otherwise
    along the specified axis.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and dtype.

Returns
-------
index_array : ndarray of ints
    Array of indices into the array. It has the same shape as `a.shape`
    with the dimension along `axis` removed.

See Also
--------
ndarray.argmax, argmin
amax : The maximum value along a given axis.
unravel_index : Convert a flat index into an index tuple.
take_along_axis : Apply ``np.expand_dims(index_array, axis)``
                  from argmax to an array as if by calling max.

Notes
-----
In case of multiple occurrences of the maximum values, the indices
corresponding to the first occurrence are returned.

Examples
--

argmax: [2 2 0 0]
argmax: [3 2 2]


In [8]:
print(f'matrix multiplication:\n {np.matmul(data1, data2)}')
?np.matmul

Call signature:  np.matmul(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'matmul'>
File:            ~/develop/pycuda_projects/pycuda_projects_env/lib/python3.8/site-packages/numpy/__init__.py
Docstring:      
matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Matrix product of two arrays.

Parameters
----------
x1, x2 : array_like
    Input arrays, scalars not allowed.
out : ndarray, optional
    A location into which the result is stored. If provided, it must have
    a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
    provided or None, a freshly-allocated array is returned.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

    .. versionadded:: 1.16
       Now handles ufunc kwargs

Returns
-------
y : ndarray
    The matrix product of the inputs.
    This is a scalar only when both x1, x2 are 1-d vectors.

Raises
------
ValueError
    If the last di

matrix multiplication:
 [[-0.42715567 -0.60589676 -0.67753045 -0.76263331]
 [ 0.29281249  0.37213008  0.52401831  0.28225297]
 [-0.20845515  0.01165464 -0.37174261  0.0139314 ]
 [-0.0723489   0.05953951 -0.1534522   0.1334377 ]]


In [9]:
for data in dataset:
    print(f'flatten:\n {data.flatten()}')
?data1.flatten

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method


flatten:
 [-0.46476243 -0.55800005  0.15796423  0.52808353 -0.26334792  0.55359871
  0.36578814 -0.44086894 -0.43840096  0.14138056  0.02824412 -0.43159136]
flatten:
 [0.44070814 0.78428961 0.71698191 0.85093412 0.49595484 0.47507437
 0.79897587 0.66162029 0.34445609 0.15005364 0.6427049  0.01287034]


In [10]:
for data in dataset:
    print(f'before type: {data.dtype}\nafte type: {type(np.array2string(data))}')
?np.array2string

before type: float64
afte type: <class 'str'>
before type: float64
afte type: <class 'str'>


Signature:
np.array2string(
    a,
    max_line_width=None,
    precision=None,
    suppress_small=None,
    separator=' ',
    prefix='',
    style=<no value>,
    formatter=None,
    threshold=None,
    edgeitems=None,
    sign=None,
    floatmode=None,
    suffix='',
    *,
    legacy=None,
)
Docstring:
Return a string representation of an array.

Parameters
----------
a : array_like
    Input array.
max_line_width : int, optional
    Inserts newlines if text is longer than `max_line_width`.
    Defaults to ``numpy.get_printoptions()['linewidth']``.
precision : int or None, optional
    Floating point precision.
    Defaults to ``numpy.get_printoptions()['precision']``.
suppress_small : bool, optional
    Represent numbers "very close" to zero as zero; default is False.
    Very close is defined by precision: if the precision is 8, e.g.,
    numbers smaller (in absolute value) than 5e-9 are represented as
    zero.
    Defaults to ``numpy.get_printoptions()['suppress']``.
separator 

In [11]:
def genOlap(nday, nproduct, nsale) -> np.ndarray:
    day = []
    for _ in range(nday):
        products = []
        for _ in range(nproduct):
            step = np.random.randint(100, 1000)
            products.append(np.random.randint(step, step*10, size=(nsale,)))
        products = np.vstack(products)
        day.append(products)
    return np.dstack(day)

In [12]:
olap = genOlap(3,3,3)
print(f'olap cube:\n {olap}')


olap cube:
 [[[3277 4031 2796]
  [2284 1349  936]
  [2679 5660 3446]]

 [[3269 2721 4429]
  [3360 3047 6652]
  [1590  939 5740]]

 [[4746  898 3178]
  [3914 1111 3700]
  [1676 1005 2412]]]


In [14]:
sample = olap[:3,:,1:3]
print(f'sample:\n{sample}\nmin axis 1 and 2 fixed:\n{sample.min(axis=(1,2))}')

sample:
[[[4031 2796]
  [1349  936]
  [5660 3446]]

 [[2721 4429]
  [3047 6652]
  [ 939 5740]]

 [[ 898 3178]
  [1111 3700]
  [1005 2412]]]
min axis 1 and 2 fixed:
[936 939 898]
